"""
routers/returns.py
------------------
Return request generation: builds a WhatsApp message + wa.me link 
and generates a ReportLab PDF for supplier handover.
"""

import os
import re
from datetime import date, datetime
from typing import Any
from urllib.parse import quote

from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.auth.dependencies import get_current_user
from app.database import get_collection
from app.models.user import UserOut

router = APIRouter(prefix="/returns", tags=["returns"])

_PDF_DIR = "/tmp/expiryguard_returns"
os.makedirs(_PDF_DIR, exist_ok=True)


# ── PDF generation helper ─────────────────────────────────────

def _generate_return_pdf(
    batch: dict,
    supplier: dict | None,
    user: UserOut,
    pdf_path: str,
) -> None:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=12,
    )

    # Header
    elements.append(Paragraph(user.shop_name, title_style))
    elements.append(Paragraph("Return Request — ExpiryGuard", sub_style))
    elements.append(Spacer(1, 0.4 * cm))

    # Details table
    expiry = batch.get("expiry_date")
    if isinstance(expiry, datetime):
        expiry = expiry.date()
    purchase = batch.get("purchase_date")
    if isinstance(purchase, datetime):
        purchase = purchase.date()

    supplier_name = supplier.get("name", "N/A") if supplier else batch.get("supplier_name", "N/A")

    table_data = [
        ["Field", "Details"],
        ["Product Name", batch.get("product_name", "N/A")],
        ["Batch Number", batch.get("batch_number", "N/A")],
        ["Expiry Date", expiry.strftime("%d/%m/%Y") if expiry else "N/A"],
        ["Purchase Date", purchase.strftime("%d/%m/%Y") if purchase else "N/A"],
        ["Quantity", str(batch.get("quantity", 0))],
        ["Purchase Price", f"₹{batch.get('purchase_price', 0):.2f}"],
        ["Supplier", supplier_name],
        ["Shop Name", user.shop_name],
        ["Contact", user.phone],
    ]

    t = Table(table_data, colWidths=[6 * cm, 11 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#f0f4ff")),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 1 * cm))

    # Footer
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.grey,
        alignment=1,
    )
    elements.append(
        Paragraph(
            f"Generated by ExpiryGuard on {date.today().strftime('%d %B %Y')}",
            footer_style,
        )
    )

    doc.build(elements)


# ── WhatsApp message builder ──────────────────────────────────

def _build_whatsapp_message(batch: dict, supplier: dict | None, user: UserOut) -> str:
    expiry = batch.get("expiry_date")
    if isinstance(expiry, datetime):
        expiry = expiry.date()
    purchase = batch.get("purchase_date")
    if isinstance(purchase, datetime):
        purchase = purchase.date()

    supplier_name = supplier.get("name", "Sir/Madam") if supplier else batch.get("supplier_name", "Sir/Madam")

    return (
        f"Hi {supplier_name},\n\n"
        f"I would like to return the following near-expiry stock:\n\n"
        f"Product: {batch.get('product_name', 'N/A')}\n"
        f"Batch No: {batch.get('batch_number', 'N/A')}\n"
        f"Expiry Date: {expiry.strftime('%d/%m/%Y') if expiry else 'N/A'}\n"
        f"Qty: {batch.get('quantity', 0)} units\n"
        f"Purchase Date: {purchase.strftime('%d/%m/%Y') if purchase else 'N/A'}\n\n"
        f"Kindly confirm receipt and arrange pickup at your earliest.\n"
        f"Shop: {user.shop_name} | Contact: {user.phone}\n\n"
        f"Thank you."
    )


def _whatsapp_url(phone: str, message: str) -> str:
    clean = re.sub(r"\D", "", phone).lstrip("91")
    return f"https://wa.me/91{clean}?text={quote(message)}"


# ── Request schema ────────────────────────────────────────────

class GenerateReturnRequest(BaseModel):
    batch_id: str


# ── Endpoints ─────────────────────────────────────────────────

@router.post("/generate")
async def generate_return(
    body: GenerateReturnRequest,
    current_user: UserOut = Depends(get_current_user),
) -> dict[str, Any]:
    if current_user.role != "shopkeeper":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Return is available only for shopkeepers",
        )

    batches = get_collection("batches")
    batch = await batches.find_one(
        {"_id": ObjectId(body.batch_id), "user_id": current_user.id}
    )
    if not batch:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Batch not found")

    # Fetch supplier if linked
    supplier: dict | None = None
    if batch.get("supplier_id"):
        suppliers = get_collection("suppliers")
        supplier = await suppliers.find_one({"_id": ObjectId(batch["supplier_id"])})

    whatsapp_msg = _build_whatsapp_message(batch, supplier, current_user)

    # Generate PDF
    pdf_filename = f"return_{body.batch_id}.pdf"
    pdf_path = os.path.join(_PDF_DIR, pdf_filename)
    try:
        _generate_return_pdf(batch, supplier, current_user, pdf_path)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF generation failed: {exc}",
        )

    supplier_phone = ""
    supplier_whatsapp = ""
    wa_url = ""
    if supplier:
        supplier_phone = supplier.get("phone", "")
        supplier_whatsapp = supplier.get("whatsapp_number") or supplier_phone
        if supplier_whatsapp:
            wa_url = _whatsapp_url(supplier_whatsapp, whatsapp_msg)
    elif batch.get("supplier_name"):
        # No linked supplier doc — use phone from batch if available
        pass

    return {
        "whatsapp_message": whatsapp_msg,
        "whatsapp_url": wa_url,
        "supplier_name": supplier.get("name") if supplier else batch.get("supplier_name"),
        "supplier_whatsapp": supplier_whatsapp,
        "pdf_filename": pdf_filename,
    }


@router.get("/pdf/{batch_id}")
async def download_return_pdf(
    batch_id: str,
    current_user: UserOut = Depends(get_current_user),
) -> FileResponse:
    """Serve the previously generated return PDF."""
    if current_user.role != "shopkeeper":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Return is available only for shopkeepers",
        )

    # Verify ownership
    batches = get_collection("batches")
    batch = await batches.find_one(
        {"_id": ObjectId(batch_id), "user_id": current_user.id}
    )
    if not batch:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Batch not found")

    pdf_filename = f"return_{batch_id}.pdf"
    pdf_path = os.path.join(_PDF_DIR, pdf_filename)

    if not os.path.exists(pdf_path):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="PDF not found. Call POST /returns/generate first.",
        )

    return FileResponse(
        path=pdf_path,
        media_type="application/pdf",
        filename=pdf_filename,
    )
